#!/usr/bin/python3

import sys
import os
import re
import shutil

ABSOLUTE_TOOLS_PATH = '/Users/nhiebl/Repositories/adventofcode/tools'

def create_python_directory():
  shutil.copyfile(ABSOLUTE_TOOLS_PATH + '/main.py', './main.py')
  open('r.txt', 'a').close()
  open('s.txt', 'a').close()
  open('s2.txt', 'a').close()

if __name__ == '__main__':
  if len(sys.argv) != 3:
    raise ValueError('Expected 3 arguments, e.g.: aoc <day00> <py|js>')

  _, folder_name, lang = sys.argv

  if not re.match(r'^day[0-9]{2}$', folder_name):
    raise ValueError('Expected second argument (folder name) to be of the form: day01')

  if not lang in ('py'):
    raise NotImplementedError('Language {} not implemented'.formated(lang))

  if os.path.isdir('./{}'.format(folder_name)):
    raise AssertionError('Folder already exists: {}'.format(folder_name))

  os.mkdir('./{}'.format(folder_name))
  os.chdir('./{}'.format(folder_name))

  if lang == 'py':
    create_python_directory()
